### ISSUE TITLE
Binding to external libraries example not working in Godot 4.2

### ISSUE THREAD

**Issue by RDaneelOlivav** [godotengine/godot-docs#8570]
**Your Godot version:**
4.2, in Ubuntu 22

**Issue description:**
```
When compiling the example of the TTS external library, it gives the following errors 

/my_env/godot_4_modules/tts/register_types.h:3:6: error: variable or field 'initialize_tts_module' declared void
    3 | void initialize_tts_module(ModuleInitializationLevel p_level);
      |      ^~~~~~~~~~~~~~~~~~~~~
/my_env/godot_4_modules/tts/register_types.h:3:28: error: 'ModuleInitializationLevel' was not declared in this scope
    3 | void initialize_tts_module(ModuleInitializationLevel p_level);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~
/my_env/godot_4_modules/tts/register_types.h:4:6: error: variable or field 'uninitialize_tts_module' declared void
    4 | void uninitialize_tts_module(ModuleInitializationLevel p_level);
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/my_env/godot_4_modules/tts/register_types.h:4:30: error: 'ModuleInitializationLevel' was not declared in this scope
    4 | void uninitialize_tts_module(ModuleInitializationLevel p_level);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 55%] /my_env/godot_4_modules/tts/register_types.cpp:8:6: error: variable or field 'initialize_tts_module' declared void
    8 | void initialize_tts_module(ModuleInitializationLevel p_level) {
      |      ^~~~~~~~~~~~~~~~~~~~~
/my_env/godot_4_modules/tts/register_types.cpp:8:28: error: 'ModuleInitializationLevel' was not declared in this scope; did you mean 'GDExtensionInitializationLevel'?
    8 | void initialize_tts_module(ModuleInitializationLevel p_level) {
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                            GDExtensionInitializationLevel
/my_env/godot_4_modules/tts/register_types.cpp:16:6: error: variable or field 'uninitialize_tts_module' declared void
   16 | void uninitialize_tts_module(ModuleInitializationLevel p_level) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/my_env/godot_4_modules/tts/register_types.cpp:16:30: error: 'ModuleInitializationLevel' was not declared in this scope; did you mean 'GDExtensionInitializationLevel'?
   16 | void uninitialize_tts_module(ModuleInitializationLevel p_level) {
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                              GDExtensionInitializationLevel
```

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/binding_to_external_libraries.html

**Comment by QueenTurtle** [comment]
I'm currently following this tutorial. 
I still haven't quite got the plugin to work yet but I noticed that the register_types.h is missing an include, I'm reusing the include from the summator example but I still don't have a fully compiled version yet. 
You could try adding `#include "modules/register_module_types.h"` to the top of register_types.h. Unfortunately I have other engagements today and time is ticking on so I'm going to have to stop tinkering for the day but maybe you'll have more luck than I'm having at the moment.
